// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Bb_yOlhGvW_pLP3iln91ES7KLaVDu8E',
    appId: '1:473385735243:android:c5571973cb3d358a0569ce',
    messagingSenderId: '473385735243',
    projectId: 'aurify-2',
    databaseURL: 'https://aurify-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aurify-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mdlXiTvRzCOTEVDu_1ryOxqMkf3bM10',
    appId: '1:473385735243:ios:1f2903490dcc756f0569ce',
    messagingSenderId: '473385735243',
    projectId: 'aurify-2',
    databaseURL: 'https://aurify-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aurify-2.firebasestorage.app',
    iosBundleId: 'com.example.crystalGold',
  );
}
